### ISSUE TITLE
NameError: name 'init' is not defined

### ISSUE THREAD

**Issue by abeburnett** [Thibauth/python-pushover#28]
Hi there,

So code which has been working for some time, is no longer working with python-pushover 1.0 running on Python 3.7. 

`from pushover import init, Client`

Used to work, but now gives the error: "NameError: name 'init' is not defined"

However, doing:

`import pushover
from pushover import Client`

Doesn't work either, giving a "ImportError: cannot import name 'Client' from 'pushover'."

Can you please advise how I should now be importing (and using) this module at version 1.0 under Python 3.7? Thank you!
